name: gymbroo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2 
  url_launcher: ^6.2.2
  http: ^1.2.1
  mime: ^1.0.0
  qr_flutter: ^4.1.0 
  uuid: ^4.4.0
  webview_flutter: ^4.7.0 
  cached_network_image: ^3.3.1 
  http_parser: ^4.0.2         
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: League Spartan
      fonts:
        - asset: fonts/LeagueSpartan-Thin.ttf
          weight: 100
        - asset: fonts/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: fonts/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: fonts/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: fonts/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: fonts/LeagueSpartan-Bold.ttf
          weight: 700
    - family: Konkhmer Sleokchher
      fonts:
        - asset: fonts/KonkhmerSleokchher-Regular.ttf